// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyhfbwbrzxrfhaxhpzir.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5aGZid2JyenhyZmhheGhwemlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMDYwMTEsImV4cCI6MjA3NDU4MjAxMX0.kl7LmsT0SDkOQZ3Mwt07ydV1D8UCmZ8W-9ookGdU4_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});